"""
Report service — powers POST /report.

The incident report for a thread is already generated by the Report
Generator Agent during /chat and persisted in the LangGraph checkpointer.
This service simply reads it back by thread_id instead of regenerating
it, so the report returned always matches exactly what the user saw.
"""

from app.graph.workflow import build_thread_config, get_workflow
from app.utils.exceptions import GuardianCouncilError
from app.utils.logger import get_logger

logger = get_logger(__name__)


class ReportNotFoundError(GuardianCouncilError):
    def __init__(self, thread_id: str):
        super().__init__(
            f"No completed incident report found for thread_id '{thread_id}'. "
            "Send a message via /chat first.",
            status_code=404,
        )


def get_report_for_thread(thread_id: str) -> dict:
    """Fetch the persisted final_report for a given conversation thread."""
    workflow = get_workflow()
    config = build_thread_config(thread_id)

    snapshot = workflow.get_state(config)
    final_report = (snapshot.values or {}).get("final_report") if snapshot else None

    if not final_report:
        raise ReportNotFoundError(thread_id)

    return final_report
